// IEEE 802.3 CRC-32 parallel calculator
// Polynomial: x^32+x^26+x^23+x^22+x^16+x^12+x^11+x^10+x^8+x^7+x^5+x^4+x^2+x+1
// Reflected algorithm (LSB-first per IEEE 802.3), init=0xFFFFFFFF
//
// Equations verified by superposition against bit-serial reference model.
// Each output bit is the XOR of the contributing crc_reg and data_in bits.
//
// crc_residue = raw crc_reg (no final XOR) - used for residue check.
// crc_out     = ~crc_reg (with FINAL_XOR=1) - this is the FCS value to transmit.
//
// After feeding DA+SA+LEN+DATA+correct_FCS through this module,
// crc_residue (raw register, no XOR) = 0xDEBB20E3
//
// crc_init - synchronous reset to 0xFFFFFFFF (one-cycle pulse, takes priority)
// data_valid - process data_in this cycle

module crc32_eth_parallel #(
    parameter FINAL_XOR = 1
)(
    input           clk,
    input           rst_n,
    input           data_valid,
    input           crc_init,
    input   [7:0]   data_in,
    output  [31:0]  crc_out,
    output  [31:0]  crc_residue
);
    reg  [31:0] crc_reg;
    wire [31:0] crc_next;

    // Correct IEEE 802.3 CRC-32 byte-parallel equations
    // Generated by superposition of bit-serial model (POLY=0xEDB88320)
    assign crc_next[ 0] = crc_reg[ 2]^crc_reg[ 8]^data_in[2];
    assign crc_next[ 1] = crc_reg[ 0]^crc_reg[ 3]^crc_reg[ 9]^data_in[0]^data_in[3];
    assign crc_next[ 2] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 4]^crc_reg[10]^data_in[0]^data_in[1]^data_in[4];
    assign crc_next[ 3] = crc_reg[ 1]^crc_reg[ 2]^crc_reg[ 5]^crc_reg[11]^data_in[1]^data_in[2]^data_in[5];
    assign crc_next[ 4] = crc_reg[ 0]^crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 6]^crc_reg[12]^data_in[0]^data_in[2]^data_in[3]^data_in[6];
    assign crc_next[ 5] = crc_reg[ 1]^crc_reg[ 3]^crc_reg[ 4]^crc_reg[ 7]^crc_reg[13]^data_in[1]^data_in[3]^data_in[4]^data_in[7];
    assign crc_next[ 6] = crc_reg[ 4]^crc_reg[ 5]^crc_reg[14]^data_in[4]^data_in[5];
    assign crc_next[ 7] = crc_reg[ 0]^crc_reg[ 5]^crc_reg[ 6]^crc_reg[15]^data_in[0]^data_in[5]^data_in[6];
    assign crc_next[ 8] = crc_reg[ 1]^crc_reg[ 6]^crc_reg[ 7]^crc_reg[16]^data_in[1]^data_in[6]^data_in[7];
    assign crc_next[ 9] = crc_reg[ 7]^crc_reg[17]^data_in[7];
    assign crc_next[10] = crc_reg[ 2]^crc_reg[18]^data_in[2];
    assign crc_next[11] = crc_reg[ 3]^crc_reg[19]^data_in[3];
    assign crc_next[12] = crc_reg[ 0]^crc_reg[ 4]^crc_reg[20]^data_in[0]^data_in[4];
    assign crc_next[13] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 5]^crc_reg[21]^data_in[0]^data_in[1]^data_in[5];
    assign crc_next[14] = crc_reg[ 1]^crc_reg[ 2]^crc_reg[ 6]^crc_reg[22]^data_in[1]^data_in[2]^data_in[6];
    assign crc_next[15] = crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 7]^crc_reg[23]^data_in[2]^data_in[3]^data_in[7];
    assign crc_next[16] = crc_reg[ 0]^crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 4]^crc_reg[24]^data_in[0]^data_in[2]^data_in[3]^data_in[4];
    assign crc_next[17] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 3]^crc_reg[ 4]^crc_reg[ 5]^crc_reg[25]^data_in[0]^data_in[1]^data_in[3]^data_in[4]^data_in[5];
    assign crc_next[18] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 2]^crc_reg[ 4]^crc_reg[ 5]^crc_reg[ 6]^crc_reg[26]^data_in[0]^data_in[1]^data_in[2]^data_in[4]^data_in[5]^data_in[6];
    assign crc_next[19] = crc_reg[ 1]^crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 5]^crc_reg[ 6]^crc_reg[ 7]^crc_reg[27]^data_in[1]^data_in[2]^data_in[3]^data_in[5]^data_in[6]^data_in[7];
    assign crc_next[20] = crc_reg[ 3]^crc_reg[ 4]^crc_reg[ 6]^crc_reg[ 7]^crc_reg[28]^data_in[3]^data_in[4]^data_in[6]^data_in[7];
    assign crc_next[21] = crc_reg[ 2]^crc_reg[ 4]^crc_reg[ 5]^crc_reg[ 7]^crc_reg[29]^data_in[2]^data_in[4]^data_in[5]^data_in[7];
    assign crc_next[22] = crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 5]^crc_reg[ 6]^crc_reg[30]^data_in[2]^data_in[3]^data_in[5]^data_in[6];
    assign crc_next[23] = crc_reg[ 3]^crc_reg[ 4]^crc_reg[ 6]^crc_reg[ 7]^crc_reg[31]^data_in[3]^data_in[4]^data_in[6]^data_in[7];
    assign crc_next[24] = crc_reg[ 0]^crc_reg[ 2]^crc_reg[ 4]^crc_reg[ 5]^crc_reg[ 7]^data_in[0]^data_in[2]^data_in[4]^data_in[5]^data_in[7];
    assign crc_next[25] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 5]^crc_reg[ 6]^data_in[0]^data_in[1]^data_in[2]^data_in[3]^data_in[5]^data_in[6];
    assign crc_next[26] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 2]^crc_reg[ 3]^crc_reg[ 4]^crc_reg[ 6]^crc_reg[ 7]^data_in[0]^data_in[1]^data_in[2]^data_in[3]^data_in[4]^data_in[6]^data_in[7];
    assign crc_next[27] = crc_reg[ 1]^crc_reg[ 3]^crc_reg[ 4]^crc_reg[ 5]^crc_reg[ 7]^data_in[1]^data_in[3]^data_in[4]^data_in[5]^data_in[7];
    assign crc_next[28] = crc_reg[ 0]^crc_reg[ 4]^crc_reg[ 5]^crc_reg[ 6]^data_in[0]^data_in[4]^data_in[5]^data_in[6];
    assign crc_next[29] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 5]^crc_reg[ 6]^crc_reg[ 7]^data_in[0]^data_in[1]^data_in[5]^data_in[6]^data_in[7];
    assign crc_next[30] = crc_reg[ 0]^crc_reg[ 1]^crc_reg[ 6]^crc_reg[ 7]^data_in[0]^data_in[1]^data_in[6]^data_in[7];
    assign crc_next[31] = crc_reg[ 1]^crc_reg[ 7]^data_in[1]^data_in[7];

    always @(posedge clk or negedge rst_n) begin
        if      (!rst_n)     crc_reg <= 32'hFFFFFFFF;
        else if (crc_init)   crc_reg <= 32'hFFFFFFFF;
        else if (data_valid) crc_reg <= crc_next;
    end

    assign crc_out     = FINAL_XOR ? ~crc_reg : crc_reg;
    assign crc_residue = crc_reg;
endmodule